#ifndef BINARYTREES_SRC_C_STATISTICS_H
#define BINARYTREES_SRC_C_STATISTICS_H

#define MAX_DEPTH 5000
#define STEP 500
#define REPETITIONS 100

#define BRANCHING_LEVELS 3

void showStats(void);

#endif //BINARYTREES_SRC_C_STATISTICS_H
