#ifndef BINARYTREES_SRC_C_TREEOPERATIONSERVICE_H
#define BINARYTREES_SRC_C_TREEOPERATIONSERVICE_H

#include <stdlib.h>

#include "File.h"
#include "BinTree.h"

#endif //BINARYTREES_SRC_C_TREEOPERATIONSERVICE_H
